#!/bin/bash -ex

ANSIBLE_VERSIONS=(
  "2.7.0"
  "2.7.4"
  "2.7.7"
)

for ANSIBLE_VERSION in "${ANSIBLE_VERSIONS[@]}"; do
  FULL_IMAGE_NAME="${DOCKER_REPO?}:${DOCKER_TAG?}-${ANSIBLE_VERSION?}"
  docker build --build-arg ANSIBLE_VERSION="${ANSIBLE_VERSION}" -f "${DOCKERFILE_PATH}" -t "${FULL_IMAGE_NAME}" ".${BUILD_PATH}"
  docker push "${FULL_IMAGE_NAME}"
done
