#!/bin/bash -ex

ANSIBLE_VERSIONS=(
  "2.4.2"
  "2.5.15"
  "2.6.14"
  "2.6.16"
  "2.7.0"
  "2.7.1"
  "2.7.2"
  "2.7.3"
  "2.7.4"
  "2.7.5"
  "2.7.6"
  "2.7.7"
  "2.7.8"
  "2.7.9"
  "2.7.10"
)

MOLECULE_VERSION="2.20.0"

for ANSIBLE_VERSION in "${ANSIBLE_VERSIONS[@]}"; do
  FULL_IMAGE_NAME="${DOCKER_REPO?}:ansible-${ANSIBLE_VERSION?}"
  docker build --build-arg ANSIBLE_VERSION="${ANSIBLE_VERSION}" --build-arg MOLECULE_VERSION="${MOLECULE_VERSION}" -f "${DOCKERFILE_PATH}" -t "${FULL_IMAGE_NAME}" ".${BUILD_PATH}"
  docker push "${FULL_IMAGE_NAME}"
done
